# Generated by Django 2.2.24 on 2021-06-20 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0001_initial'),
        ('estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='clase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clases.Clase'),
        ),
    ]
