# Generated by Django 2.2.24 on 2021-06-21 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0001_initial'),
        ('estudiantes', '0002_estudiante_clase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='clase',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='clase',
            field=models.ManyToManyField(related_name='clases', to='clases.Clase'),
        ),
    ]
